// Code generated by mockery v2.40.1. DO NOT EDIT.

package repomocks

import (
	discount "wallet/client/discount"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetGiftByCode provides a mock function with given fields: code
func (_m *Client) GetGiftByCode(code string) (*discount.Gift, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetGiftByCode")
	}

	var r0 *discount.Gift
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*discount.Gift, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *discount.Gift); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*discount.Gift)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseGift provides a mock function with given fields: code
func (_m *Client) UseGift(code string) (*discount.Gift, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for UseGift")
	}

	var r0 *discount.Gift
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*discount.Gift, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *discount.Gift); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*discount.Gift)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
